const actionTypes = {
  ADD_STUDENT : "ADD_STUDENT",
  DELETE_STUDENT : "DELETE_STUDENT",
  EDIT_STUDENT : "EDIT_STUDENT",
  GET_STUDENT_REQUEST: "GET_STUDENT_REQUEST",
  GET_STUDENT_FULFILLED: "GET_STUDENT_FULFILLED"
}

export default actionTypes;
