const actionTypes = {
  ADD_STUDENT : "ADD_STUDENT",
  DELETE_STUDENT : "DELETE_STUDENT",
  EDIT_STUDENT : "EDIT_STUDENT",
  GET_STUDENT: "GET_STUDENT",
  GET_GRADE_AVERAGE: "GET_GRADE_AVERAGE",
  GET_SEARCH: "GET_SEARCH",
  SEARCH_STUDENT: "SEARCH_STUDENT"
}

export default actionTypes;
